### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by BrainSlayer** [opnsense/dhcp6c#11]
i told you what exactly is wrong and never blamed you how bad you are. so fix it or keep it as is. i'm not interested of sending pull requests to people who are not accepting that there might be a bug. i described it really in detail and the difference between pointers and numeric 64 bit values should be clear to any programmer . thanks.

**Comment by fichtner** [comment]
https://github.com/opnsense/dhcp6c/issues/8#issuecomment-469758541
