### ISSUE TITLE
Get delegated prefix information in script

### ISSUE THREAD

**Issue by hardillb** [opnsense/dhcp6c#19]
Is there a way to get information about delegated prefixes passed to the script?

I'm running a system where 2 prefix are delegated:

 - The first is normal /64 prefix that I'm attaching to an interface for normal SLAAC address allocation.
 - The second is a /96 or /120 that I'm using for 464XLAT that I need to pass to an instance of [Jool](https://www.jool.mx/en/index.html) running on the router. At the moment I'm having to hardcode/manually enter this.

If not can I ask for it to be a feature request?

**Comment by fichtner** [comment]
Will be the case via #28 eventually.
