### ISSUE TITLE
Wrong advertized link layer address?

### ISSUE THREAD

**Issue by tbarbette** [opnsense/dhcp6c#35]
The link layer address advertised with the SOLICIT request is not the one of the interface I run dhcp6c on. It's the address of an unrelated interface. It's neither WAN, neither LAN. 

![Capture d’écran 2024-01-18 à 12 34 02](https://github.com/opnsense/dhcp6c/assets/248961/f12af374-e5c8-4710-8682-ba5f719025a8)

Any idea how that could happen? Not sure which of the two is the problem. The configuration:

```
profile default
{
  information-only;

  request domain-name-servers;
  request domain-name;

  script "/etc/wide-dhcpv6/dhcp6c-script";
};


interface internet0 {
  send ia-pd 3337356211;
  request domain-name-servers;
  request domain-name;
  request ntp-servers;
  script "/etc/wide-dhcpv6/dhcp6c-script";
};

id-assoc pd 3337356211 {
 prefix-interface br0 { #internal facing interface (LAN)
    sla-id 1; 
    ifid 1; 
    sla-len 8;
    };
  };

```

**Comment by fichtner** [comment]
Sorry, not sure what happened here but don't have more information so I'm closing. The bridge might be a problem.
