### ISSUE TITLE
Parsing configuration failed at startup if request is tracked by a bridged interface

### ISSUE THREAD

**Issue by tduboys** [opnsense/dhcp6c#7]
Hi,

I'm using OPNSense following this setup : https://wiki.opnsense.org/manual/how-tos/orange_fr_fttp.html

My box is set up as : 
- igb0 as WAN
- igb1, igb2, igb3… as bridge0
- bridge0 as LAN

On startup, dhcp6c client parses the config file and see that my LAN interface (bridge0) is tracking the WAN interface to get IPv6 configuration, but bridge0 is not set up at this moment, so the config fails and dhcp6c didnt start.
```
Jan  8 20:19:12 opnsense dhcp6c[38999]: /var/etc/dhcp6c_wan.conf:13 invalid interface (bridge0): Device not configured
Jan  8 20:19:12 opnsense dhcp6c[38999]: called
Jan  8 20:19:12 opnsense dhcp6c[38999]: failed to parse configuration file
```

I need to force a dhcp refresh after startup to get IPv6

How to reproduce : 
- set up a WAN interface with dhcp6c
- set up a LAN interface with bridge on multiple physical interfaces
- set up id-assoc to the bridge interface 
```
id-assoc pd 0 {
  prefix-interface bridge0 {
    sla-id 0;
    sla-len 8;
  };
};

```
- reboot
- see logs

What expected : 
- no errors during boot, ipv6 working directly

**Comment by marjohn56** [comment]
Odd, I use a bridge interface on my test unit, never have any issues, but Ill double check it. This is not really an issue with dhcp6 itself but the core routines that generate the config files.

**Comment by tduboys** [comment]
> Odd, I use a bridge interface on my test unit, never have any issues, but Ill double check it. This is not really an issue with dhcp6 itself but the core routines that generate the config files.

Hi, I suppose that it's not really on dhcp6c but I dont really know where to talk about.
Probably the resolution should be to delay the start of dhcp6c after all bridges.
If you know where is the good place to discuss about that ? :)

**Comment by marjohn56** [comment]
Try [https://github.com/opnsense/core/issues](url)

**Comment by fichtner** [comment]
So question is this: radvd.conf has an option IgnoreIfMissing -- we could implement something like this  in dhcp6c instead of rearranging a lot of core code. Or we close this and focus on #3199, which is probably the better approach in the long run.

**Comment by marjohn56** [comment]
Cannot answer that as I am on my hols..I'll think about it whilst I am sipping on a cold beer by the pool.

**Comment by fichtner** [comment]
@marjohn56 please do enjoy 👍

**Comment by marjohn56** [comment]
I will try but it will be difficult...

**Comment by fichtner** [comment]
Going for a core fix...
