### ISSUE TITLE
ia-pd and ia-na T1 and T2 values

### ISSUE THREAD

**Issue by djzort** [opnsense/dhcp6c#9]
Is there any way to set the T1 and T2 values for ia-pd and ia-na options?

The doco doesnt seem to have a way, im about to dive in to the code...

**Comment by djzort** [comment]
As far as i can tell theyre hard coded to 0

**Comment by nivek1612** [comment]
I looked at this a while ago with @marjohn56.

Its a significant effort to add this to dhcp6c and as its ignored by most ISP's anyway it was assumed to not be worth the effort right now. Are you seeing issues ?

**Comment by djzort** [comment]
I believed this to be the cause of problems, but it turned out to be unrelated.
If there is no way currently, then you have answered my question :)

It does look like opnsense is the only people giving wide-dhcp6 any love (and only a little bit) - perhaps the isc client via the dual-dhclient port would be better?

**Comment by nivek1612** [comment]
there has been a huge amount of work from the team on it. :-)

Before they did this work many of the dhcp6c options where not passed but now Raw-options are supported fully. 

so whilst you can't send T1 & T2 as options you can build a raw-option 25 which is made up of IAID, T1 & T2

**Comment by fichtner** [comment]
Timeout.

**Comment by tbarbette** [comment]
Hi! I think this is causing my ISP to ignore the message too. Maybe @djzort what was the reason of your problem?

Basically I'm looking in wireshark dhclient -6 -P is working:
![Capture d’écran 2024-01-18 à 12 30 26](https://github.com/opnsense/dhcp6c/assets/248961/66f0b9ee-fc5c-4fbe-9c1f-77f10c2c2d87)

And with dhcp6c:
![Capture d’écran 2024-01-18 à 12 34 02](https://github.com/opnsense/dhcp6c/assets/248961/f12af374-e5c8-4710-8682-ba5f719025a8)

I don't see anything else different, except maybe the FQDN request missing. My ISP is Proximus (Belgium).

**Comment by tbarbette** [comment]
It also seems the link layer address being advertised is wrong. I'll open a dedicated issue.
